config/routes.rb
Bicing::Application.routes.draw do
  resources :samples do
    resources :statuses
  end

  resources :stations do
    resources :statuses
  end

  root :to => "main#index"
  
  match 'update_data' => "samples#update_data"

end

app/models/sample.rb
class Sample < ActiveRecord::Base
  has_many :statuses

  def stats
    empty_stations = 0
    available = 0
    free_space = 0
    not_empty_stations = 0

    self.statuses.each do |status|
      available += status.available
      free_space += status.free_space
      if status.available == 0
        empty_stations += 1
      else
        not_empty_stations += 1
      end
    end

    {:empty_stations => empty_stations, :available => available, :free_space => free_space, :not_empty_stations => not_empty_stations}
  end

  def self.create_from_remote
    begin
      result = Net::HTTP.get(URI.parse(Bicing::Application.config.global["samples_service_url"]))
      remote_statuses = ActiveSupport::JSON.decode(result)
      time = Time.now
      conversor = Iconv.new('UTF-8', 'WINDOWS-1252')

      sample = Sample.create
      remote_statuses.each do |remote_status|
        status = Status.new(
          :free_space => remote_status["foratsBuits"].to_i,
          :available => remote_status["foratsPlens"].to_i,
          :station_id => remote_status["id"],
          :timestamp => time,
          :coordinates => "#{remote_status['x']}, #{remote_status['y']}",
          :name => conversor.conv(remote_status["direccio"])
        )
        status.sample = sample
        status.save
      end

      true
    rescue
      false
    end
  end
end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :sample
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  # GET /
  def index
  	
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  # GET /samples
  # GET /samples.xml
  def index
    @samples = Sample.paginate(:page => params[:page]).order('created_at desc')

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @samples }
      format.json { render :json => @samples }
    end
  end

  # GET /samples/1
  # GET /samples/1.xml
  def show
    @sample = Sample.find(params[:id])
    @stats = @sample.stats

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sample }
      format.json { render :json => @sample }
    end
  end

  # GET /update_data?token=123
  # GET /update_data.xml?token=123
  def update_data
    if token_is_valid?
      if Sample.create_from_remote
        flash[:notice] = "Data updated"
      else
        flash[:notice] = "Data not updated. Please wait a few minutes"
      end
    else
      flash[:notice] = "Error"
    end

    respond_to do |format|
      format.html { redirect_to root_url }
      format.xml  { head :ok }
      format.json { head :ok }
    end
    
  end

private

  def token_is_valid?
    params[:token] == Bicing::Application.config.global["token"]
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  # GET /stations/1
  # GET /stations/1.xml
  def show
    @station = params[:id]
    @statuses = Status.where(:station_id => @station).paginate(:page => params[:page]).order('timestamp asc')
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  # GET /statuses
  # GET /statuses.xml
  def index
    @sample = Sample.find(params[:sample_id])
    @statuses = @sample.statuses
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @statuses }
      format.json { render :json => @statuses }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def pagination(what)
    "#{will_paginate what, :id => 'paginator', :class => 'apple_pagination'}".html_safe
  end
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/layouts/_normal.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>bicingstats</title>
  <%= stylesheet_link_tag @common_stylesheets %>
  <%= stylesheet_link_tag  'normal', 'tables', :media => 'screen' %>
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <%= javascript_include_tag @common_javascripts  %>
  <%= javascript_include_tag 'jquery.cookie' %>
  <%= javascript_include_tag 'jquery.json' %>
  <%= javascript_include_tag 'jquery.datatables' %>
  <link href='http://fonts.googleapis.com/css?family=Maven+Pro|Varela' rel='stylesheet' type='text/css' />
  <%= csrf_meta_tag %>
  <script type="text/javascript">
    $(document).ready(function(){
      init('normal');
    });
  </script>
</head>
<body>
  <div id="wrapper">
    <div id="header">
      <div id="logo">
        <a href="/"><span class="orange">bicing</span>stats</a>
      </div>
      <div id="user">
        <span class="button_links">
        </span>
      </div>
      <div class="clear"></div>
      <div id="tagline"></div>
    </div>
    <div id="menu">
      <%= render 'shared/menu' %>
    </div>
    <div id="content">
      <% if notice %>
        <p class="notice"><%= notice %></p>
      <% end %>
       <% if alert %>
        <p class="alert"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
    <div id="footer">Copyright &copy; 2011 -2012 <a href="http://nosolopau.com" target="_blank">Pau</a></div>
    <div class="clear"></div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<% @common_stylesheets = ['global'] %>
<% @common_javascripts = ['application', 'jquery', 'rails', 'jquery.metadata', 'jquery.corner'] %>

<%= render 'layouts/normal' %>

app/views/main/error.html.erb
<h1>Error</h1>
<p><%= alert %></p>

app/views/main/index.html.erb
<h1>About</h1>
<p>This application provides an historic record of the occupation data of the Barcelona's <a href="http://bicing.cat">bicing</a> system.</p>
<p>This data is available via <%= link_to 'web',  samples_path %>, <%= link_to 'json', samples_path(:format => :json) %>
and <%= link_to 'xml', samples_path(:format => :xml) %>.</p>
<h2>Acknowledges</h2>
<p>This application uses the <%= link_to 'Bicing API', 'http://rocboronat.net/index.php/es/projectes/48-bicing-api' %> by <%= link_to 'Roc Boronat', 'http://rocboronat.net/' %>.</p>

app/views/samples/index.html.erb
<h1>Samples</h1>
<p>
  <span class="button_links">
    <%= link_to 'html', samples_path %>
    <%= link_to 'json', samples_path(:format => :json) %>
    <%= link_to 'xml',  samples_path(:format => :xml) %>
  </span>
</p>
<table id="sorted_table" class="tablesorter">
  <thead>
    <tr>
      <th>Id.</th>
      <th>Timestamp</th>
      <th>Available</th>
      <th>Free space</th>
      <th>Total</th>
      <th>Empty stations</th>
      <th>Not empty stations</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @samples.each do |sample| %>
    <% @stats = sample.stats %>
      <tr>
        <td><%= link_to sample.id, sample_statuses_path(sample) %></td>
        <td><%= sample.created_at %></td>
        <td><%= @stats[:available] %></td>
        <td><%= @stats[:free_space] %></td>
        <td><%= @stats[:free_space] + @stats[:available] %></td>
        <td><%= @stats[:empty_stations] %></td>
        <td><%= @stats[:not_empty_stations] %></td>
        <td><%= link_to 'show stats', sample %> <%= link_to 'show status', sample_statuses_path(sample) %></td>
      </tr>
    <% end %>
   </tbody>
</table>
<%= pagination @samples %>

app/views/samples/show.html.erb
<h1>Sample <%= @sample.id %></h1>
<p>Sample obtained at <%= @sample.created_at %></p>
<h2>Stats</h2>
<ul>
  <li>Available bikes: <strong><%= @stats[:available] %></strong></li>
  <li>Free space: <strong><%= @stats[:free_space] %></strong></li>
  <li>Empty stations: <strong><%= @stats[:empty_stations] %></strong></li>
  <li>Not-empty stations: <strong><%= @stats[:not_empty_stations] %></strong></li>
</ul>

app/views/shared/_menu.html.erb
<ul>
  <li><a href="/">About</a></li>
  <li><%= link_to 'Samples', samples_path %></li>
</ul>

app/views/stations/show.html.erb
<script type="text/javascript">
  google.load("visualization", "1", {packages:["corechart"]});
  google.setOnLoadCallback(drawChart);
  function drawChart() {
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Time');
    data.addColumn('number', 'Available bikes');
    data.addRows([
      <% @statuses.each do |status| %>
        ['<%= status.timestamp.strftime("%H:%M") %>', <%= status.available %>],
      <% end %>
    ]);

    var options = {
      title: 'Available bikes',
      hAxis: {slantedTextAngle: '90', slantedText: true}
    };

    var chart = new google.visualization.AreaChart(document.getElementById('chart_div'));
    chart.draw(data, options);
  }
</script>
<h1>Stats for station <%= @station %></h1>
<p>
  <span class="button_links">
    <%= link_to 'html', station_statuses_path(@station) %>
    <%= link_to 'json', station_statuses_path(@station, :format => :json) %>
    <%= link_to 'xml',  station_statuses_path(@station, :format => :xml) %>
  </span>
</p>
<div id="chart_div"></div>
<table id="sorted_table" class="tablesorter">
  <thead>
    <tr>
      <th>Id.</th>
      <th>Station id</th>
      <th>Available</th>
      <th>Free space</th>
      <th>Timestamp</th>
    </tr>
  </thead>
  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.id %></td>
        <td><%= status.station_id %></td>
        <td><%= status.available %></td>
        <td><%= status.free_space %></td>
        <td><%= status.timestamp %></td>
      </tr>
    <% end %>
   </tbody>
</table>
<%= pagination @statuses %>

app/views/statuses/index.html.erb
<h1>Statuses for sample <%= @sample.id %></h1>
<p>Sample obtained at <%= @sample.created_at %></p>
<p>
  <span class="button_links">
    <%= link_to 'html', sample_statuses_path(@sample) %>
    <%= link_to 'json', sample_statuses_path(@sample, :format => :json) %>
    <%= link_to 'xml',  sample_statuses_path(@sample, :format => :xml) %>
  </span>
</p>
<table id="sorted_table" class="tablesorter">
  <thead>
    <tr>
      <th>Id.</th>
      <th>Station id</th>
      <th>Station name</th>
      <th>Available</th>
      <th>Free space</th>
      <th>Timestamp</th>
    </tr>
  </thead>
  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.id %></td>
        <td><%= link_to status.station_id, station_path(status.station_id) %></td>
        <td><%= status.name %></td>
        <td><%= status.available %></td>
        <td><%= status.free_space %></td>
        <td><%= status.timestamp %></td>
      </tr>
    <% end %>
   </tbody>
</table>